# Copyright 2026 Jayce-Ping
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Dependency-neutral framework contracts."""

from .execution import (
    OFFLINE_EXECUTION_CONTRACT,
    ONLINE_EXECUTION_CONTRACT,
    ONLINE_NO_FEEDBACK_EXECUTION_CONTRACT,
    AcquisitionMode,
    ExecutionContract,
    FeedbackMode,
)
from .feedback import (
    FeedbackReducerContract,
    RewardCombinationOrder,
    resolve_feedback_reducer_contract,
)
from .media import (
    DECODED_AUDIO_REPRESENTATION,
    DECODED_IMAGE_REPRESENTATION,
    DECODED_VIDEO_REPRESENTATION,
    MODEL_IMAGE_REPRESENTATION,
    MODEL_VIDEO_REPRESENTATION,
    UNIT_VIDEO_REPRESENTATION,
    MediaColorSpace,
    MediaContainer,
    MediaDevice,
    MediaDType,
    MediaFormat,
    MediaGeometry,
    MediaLayout,
    MediaMetadataLike,
    MediaRepresentation,
    MediaType,
    MediaValueRange,
    RateRequirement,
    validate_media_geometry,
    validate_media_metadata,
)
from .model_condition import (
    FORWARD_STATE_BOUNDARY_KEYS,
    FORWARD_STATE_OWNED_KEYS,
    NON_MODEL_CONDITION_KEYS,
    OFFLINE_PROVENANCE_KEYS,
    ROLLOUT_STORAGE_KEYS,
    TRAINER_METADATA_KEYS,
)
from .pipeline_io import (
    BatchCapability,
    DecodedMediaLike,
    GeometrySource,
    InputMediaBinding,
    InputMediaLike,
    InputMediaOrder,
    InputMediaRule,
    InputMediaSpec,
    ModelInputLike,
    NegativePromptPolicy,
    OutputMediaLike,
    OutputMediaSequence,
    PipelineIOContract,
    resolve_pipeline_input_media_slots,
    validate_pipeline_model_input,
    validate_pipeline_output_candidate,
)
from .reward_overlap import (
    COUPLED_REWARD_OPTIMIZATION_OVERLAP,
    GLOBAL_BATCH_REWARD_OPTIMIZATION_OVERLAP,
    GROUP_RELATIVE_REWARD_OPTIMIZATION_OVERLAP,
    NO_REWARD_OPTIMIZATION_OVERLAP,
    RANK_LOCAL_REWARD_OPTIMIZATION_OVERLAP,
    WHOLE_GROUP_BATCH_REWARD_OPTIMIZATION_OVERLAP,
    RewardOptimizationOverlapContract,
    RewardTileScheduling,
)
from .sampler import (
    FLEXIBLE_SAMPLER_SELECTION,
    GLOBAL_BATCH_SAMPLER_SELECTION,
    RANK_LOCAL_SAMPLER_SELECTION,
    SAMPLER_LAYOUT_CONTRACTS,
    SAMPLER_NAME_ALIASES,
    WHOLE_GROUP_BATCH_SAMPLER_SELECTION,
    CanonicalSamplerLayout,
    GroupPlacement,
    SamplerLayoutContract,
    SamplerSelectionContract,
    get_sampler_layout_contract,
)

__all__ = [
    "AcquisitionMode",
    "BatchCapability",
    "COUPLED_REWARD_OPTIMIZATION_OVERLAP",
    "CanonicalSamplerLayout",
    "GROUP_RELATIVE_REWARD_OPTIMIZATION_OVERLAP",
    "GLOBAL_BATCH_REWARD_OPTIMIZATION_OVERLAP",
    "DecodedMediaLike",
    "DECODED_AUDIO_REPRESENTATION",
    "DECODED_IMAGE_REPRESENTATION",
    "DECODED_VIDEO_REPRESENTATION",
    "ExecutionContract",
    "FeedbackMode",
    "FeedbackReducerContract",
    "FLEXIBLE_SAMPLER_SELECTION",
    "FORWARD_STATE_BOUNDARY_KEYS",
    "FORWARD_STATE_OWNED_KEYS",
    "GeometrySource",
    "GroupPlacement",
    "GLOBAL_BATCH_SAMPLER_SELECTION",
    "InputMediaBinding",
    "InputMediaLike",
    "InputMediaOrder",
    "InputMediaRule",
    "InputMediaSpec",
    "MediaContainer",
    "MediaColorSpace",
    "MediaDType",
    "MediaDevice",
    "MediaFormat",
    "MediaGeometry",
    "MediaLayout",
    "MediaMetadataLike",
    "MediaRepresentation",
    "MediaType",
    "MediaValueRange",
    "MODEL_IMAGE_REPRESENTATION",
    "MODEL_VIDEO_REPRESENTATION",
    "ModelInputLike",
    "NegativePromptPolicy",
    "NON_MODEL_CONDITION_KEYS",
    "NO_REWARD_OPTIMIZATION_OVERLAP",
    "RANK_LOCAL_REWARD_OPTIMIZATION_OVERLAP",
    "RANK_LOCAL_SAMPLER_SELECTION",
    "OFFLINE_EXECUTION_CONTRACT",
    "OFFLINE_PROVENANCE_KEYS",
    "ONLINE_EXECUTION_CONTRACT",
    "ONLINE_NO_FEEDBACK_EXECUTION_CONTRACT",
    "OutputMediaLike",
    "OutputMediaSequence",
    "PipelineIOContract",
    "RateRequirement",
    "RewardOptimizationOverlapContract",
    "RewardCombinationOrder",
    "RewardTileScheduling",
    "WHOLE_GROUP_BATCH_REWARD_OPTIMIZATION_OVERLAP",
    "SAMPLER_LAYOUT_CONTRACTS",
    "SAMPLER_NAME_ALIASES",
    "SamplerLayoutContract",
    "SamplerSelectionContract",
    "WHOLE_GROUP_BATCH_SAMPLER_SELECTION",
    "get_sampler_layout_contract",
    "resolve_pipeline_input_media_slots",
    "resolve_feedback_reducer_contract",
    "ROLLOUT_STORAGE_KEYS",
    "TRAINER_METADATA_KEYS",
    "UNIT_VIDEO_REPRESENTATION",
    "validate_media_geometry",
    "validate_media_metadata",
    "validate_pipeline_model_input",
    "validate_pipeline_output_candidate",
]
